### ISSUE TITLE
Error while starting the app.py

### ISSUE THREAD

**Issue by alanbosco** [makefile/objdet_web#1]
INFO:root:Loading net and associated files...
Traceback (most recent call last):
  File "app.py", line 307, in <module>
    start_from_terminal(app)
  File "app.py", line 294, in start_from_terminal
    app.clf = ImagenetClassifier(**ImagenetClassifier.default_args)
  File "app.py", line 192, in __init__
    self.net = darknet.load_net(base_dir + "PLANE/yolo-voc.2.0.cfg", base_dir + "backup/yolo-voc_26000.weights", 0)
AttributeError: module 'darknet' has no attribute 'load_net'

**Comment by makefile** [comment]
The app.py is an example script for detection by using Caffe or Darknet YOLO models. You need modify and write your own code for underlying detection functions.

**Comment by alanbosco** [comment]
Ya i figured it out, ty btw.
